language: generic
dist: trusty
sudo: required

cache:
  directories:
    - .vagga/.cache

install:
  - "echo ubuntu-mirror: http://mirrors.us.kernel.org/ubuntu/ > ~/.vagga.yaml"
  - "echo alpine-mirror: http://mirrors.gigenet.com/alpinelinux/ >> ~/.vagga.yaml"
  - "echo travis:100000:65536 | sudo tee /etc/subuid | sudo tee /etc/subgid"
  - sudo apt-get install uidmap -y
  - curl http://files.zerogw.com/vagga/vagga-install-testing.sh | sh

before_deploy:
  - ./deploy/setup.sh

script:
  - vagga _build redis-trunk
  - vagga _build celery-trunk
  - vagga _build php-trunk
  - vagga _build mysql-trunk
  - vagga _build static-trunk
  - vagga _build elastic-trunk

deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      ./deploy/script.sh
      --project tabun
      --type trunk
      --containers "static redis celery php mysql elastic"
      --destination $deploy_destination
      --server $deploy_host
      --port $deploy_port
      --user $deploy_user
    on:
      branch: development

  - provider: script
    skip_cleanup: true
    script: >-
      ./deploy/script.sh
      --project tabun
      --type trunk
      --containers "static redis celery php mysql elastic"
      --destination $deploy_destination
      --server work
      --dry-run
    on:
      branch: ssh_multiplexing

  - provider: script
    skip_cleanup: true
    script: >-
      ./deploy/script.sh
      --project tabun
      --type production
      --containers "static redis celery php mysql elastic"
      --destination $deploy_destination
      --server $deploy_host
      --port $deploy_port
      --user $deploy_user
      --dry-run
    on:
      tags: true
      branch: master
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+.[0-9]+(-[a-z]+([0-9]+)?)?$
